version: '3'
services:
  robotframework:
    image: "pmnhat/robotframework:latest"
    ports:
    - "80:80"
    - "5900:5900"
    - "22:22"
    - "4444:4444"
    deploy:
      restart_policy:
        condition: on-failure
