version: '3'
services:
  robotframework:
    image: "pmnhat/robotframework:latest"
    ports:
    - "8080:80"
    - "5901:5900"
    - "23:22"
    - "4444:4444"
    deploy:
      restart_policy:
        condition: on-failure
